name: Continuous Deployment

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build Project
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '17'
          cache: 'maven'

      - name: Build with Maven
        run: ./mvnw clean package -DskipTests

      - name: Upload JAR artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-jar
          path: target/*.jar

  docker-publish:
    name: Publish to Docker Hub
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download JAR artifact
        uses: actions/download-artifact@v4
        with:
          name: app-jar
          path: target

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/arm64
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/${{ github.event.repository.name }}:latest
            ${{ secrets.DOCKER_USERNAME }}/${{ github.event.repository.name }}:${{ github.sha }}

  deploy-on-ec2:
    name: Deploy on EC2
    runs-on: ubuntu-latest
    needs: docker-publish

    steps:
      - name: Generate SSH key
        run: |
          ssh-keygen -t rsa -b 4096 -f github-actions-key -N ""

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Push temporary EC2 SSH key
        run: |
          EC2_AZ=$(aws ec2 describe-instances \
          --instance-ids ${{ secrets.EC2_INSTANCE_ID }} \
          --query "Reservations[0].Instances[0].Placement.AvailabilityZone" \
          --output text)
          
          aws ec2-instance-connect send-ssh-public-key \
            --instance-id ${{ secrets.EC2_INSTANCE_ID }} \
            --availability-zone $EC2_AZ \
            --instance-os-user ${{ secrets.EC2_USER }} \
            --ssh-public-key file://github-actions-key.pub

      - name: Fix SSH key permissions
        run: chmod 600 github-actions-key

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: github-actions-key
          script: |
            echo "Pulling application latest Docker image"
            docker pull ${{ secrets.DOCKER_USERNAME }}/${{ github.event.repository.name }}:latest
            
            echo "Stopping previous container..."
            docker rm -f ${{ github.event.repository.name }} || true
            
            echo "Writing environment variables"
            echo "${{ secrets.ENVIRONMENT_VARIABLES }}" > app.env
            
            echo "Starting new container..."
            docker run -d \
              --name ${{ github.event.repository.name }} \
              --env-file app.env \
              -p 80:8080 \
              ${{ secrets.DOCKER_USERNAME }}/${{ github.event.repository.name }}:latest
            
            echo "Cleaning .env"
            rm app.env